version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8081"
    environment:
      - DB_CONNECTION=mongodb://mongodb:27017/mydb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
