version: '3.8'

services:
  # Conteneur pour le backend Node.js
  node-app:
    build: .
    container_name: node-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - influxdb
    volumes:
      - .:/app
    networks:
      - timeseries-network

  # Conteneur pour la base de données InfluxDB
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=oXi1DYPt11DvTWEOa5gYGNn_H1A4yYXTGa6Y1_FAAWlb5bUODWgIJuD0nC9f-fYvE63gevfUhYKzKcXhlRrPxw==
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - timeseries-network

volumes:
  influxdb-data:

networks:
  timeseries-network:
